import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import fs from 'fs';
import path from 'path';
import {defineConfig} from 'vite';
import {seoPlugin} from './vite-seo-plugin';

// The site is served from the custom domain https://quinarch.design (GitHub Pages),
// i.e. from the root path, so no repo-name prefix is needed.
const BASE_PATH = '/';

// One page per gallery project, generated by scripts/generate-project-pages.mjs.
const PROJECT_PAGES = Object.fromEntries(
  fs
    .readdirSync(path.resolve(__dirname, 'projects'), { withFileTypes: true })
    .filter((d) => d.isDirectory() && fs.existsSync(path.resolve(__dirname, 'projects', d.name, 'index.html')))
    .map((d) => [`project-${d.name}`, path.resolve(__dirname, 'projects', d.name, 'index.html')]),
);

export default defineConfig(() => {
  return {
    base: BASE_PATH,
    plugins: [react(), tailwindcss(), seoPlugin()],
    resolve: {
      alias: {
        '@': path.resolve(__dirname, '.'),
      },
    },
    build: {
      // Multi-page build: the homepage plus real, independently-crawlable static pages, each with
      // its own <title>/meta/schema in its own HTML. No client-side router: vite-seo-plugin.ts
      // prerenders every page listed here into its HTML and adds it to sitemap.xml.
      rollupOptions: {
        input: {
          main: path.resolve(__dirname, 'index.html'),
          servicesHub: path.resolve(__dirname, 'services/index.html'),
          servicesVisualization: path.resolve(__dirname, 'services/visualization/index.html'),
          servicesBimCad: path.resolve(__dirname, 'services/bim-cad-drafting/index.html'),
          servicesConsultancy: path.resolve(__dirname, 'services/consultancy/index.html'),
          caseStudiesHub: path.resolve(__dirname, 'case-studies/index.html'),
          caseStudyBeachHouse: path.resolve(__dirname, 'case-studies/texas-coastal-beach-house/index.html'),
          caseStudySlamburger: path.resolve(__dirname, 'case-studies/slamburger-restaurant/index.html'),
          caseStudyCranResidence: path.resolve(__dirname, 'case-studies/cran-residence/index.html'),
          caseStudyUrbanFlats: path.resolve(__dirname, 'case-studies/urban-multi-family-flats/index.html'),
          guideLod: path.resolve(__dirname, 'guides/lod-guide/index.html'),
          scopeEstimator: path.resolve(__dirname, 'scope-estimator/index.html'),
          testSheet: path.resolve(__dirname, 'test-sheet/index.html'),
          forHomeowners: path.resolve(__dirname, 'for-homeowners/index.html'),
          designPhilosophy: path.resolve(__dirname, 'design-philosophy/index.html'),
          projects: path.resolve(__dirname, 'projects/index.html'),
          whyWorkWithUs: path.resolve(__dirname, 'why-work-with-us/index.html'),
          ...PROJECT_PAGES,
          notFound: path.resolve(__dirname, '404.html'),
        },
      },
    },
  };
});
