// Generated by scripts/generate-project-pages.mjs from src/data/projectPages.json
import { PageShell } from "../components/PageShell";
import { GalleryProjectPage } from "../pages/GalleryProjectPage";
import { projectBySlug } from "../data/galleryProjects";
import { mountPage } from "./mountPage";

const project = projectBySlug("vip-lounge-dubai")!;

export const render = mountPage((specialist) => (
  <PageShell specialist={specialist}>
    <GalleryProjectPage project={project} />
  </PageShell>
));
