// Generated by scripts/build-ribbon-assets.mjs — do not edit by hand.
// RIBBON_FILES: every image a filmstrip can show, as published (paths under public/portfolio/), with
// its size. RIBBON_OF: for each gallery image, the file its filmstrip shows — the image itself when
// it's already light enough, otherwise its copy under ribbon/ (drawing sheets trimmed to the drawing).

export const RIBBON_FILES: Record<string, { w: number; h: number }> = {
  "bimcad-workflow/originals/03-barndominium-plan-and-script.webp": {
    "w": 1920,
    "h": 1041
  },
  "bimcad-workflow/originals/04-slat-wall-model-and-script.webp": {
    "w": 1920,
    "h": 1038
  },
  "exterior-showcase/pavilion-restaurant/02-3d-model.webp": {
    "w": 2007,
    "h": 1011
  },
  "furniture-showcase/1-chairs/01-lounge-chair-cognac-velvet.webp": {
    "w": 690,
    "h": 790
  },
  "furniture-showcase/1-chairs/02-boucle-tub-chair-steel-frame.webp": {
    "w": 655,
    "h": 669
  },
  "furniture-showcase/1-chairs/03-wave-lounge-chair-burgundy-velvet.webp": {
    "w": 764,
    "h": 617
  },
  "furniture-showcase/1-chairs/04-armchair-floral-linen-turned-walnut.webp": {
    "w": 749,
    "h": 810
  },
  "furniture-showcase/1-chairs/05-cocoon-armchair-ivory-and-oak.webp": {
    "w": 847,
    "h": 745
  },
  "furniture-showcase/1-chairs/06-low-lounge-chair-chocolate-velvet.webp": {
    "w": 739,
    "h": 713
  },
  "furniture-showcase/1-chairs/07-mid-century-lounge-chair-walnut-frame.webp": {
    "w": 674,
    "h": 654
  },
  "furniture-showcase/1-chairs/08-wrapped-armchair-ivory-on-walnut.webp": {
    "w": 709,
    "h": 690
  },
  "furniture-showcase/1-chairs/09-barrel-chair-oak-shell.webp": {
    "w": 701,
    "h": 669
  },
  "furniture-showcase/1-chairs/10-club-armchair-taupe-leather.webp": {
    "w": 898,
    "h": 771
  },
  "furniture-showcase/1-chairs/11-wingback-lounge-chair-oatmeal-knit.webp": {
    "w": 952,
    "h": 928
  },
  "furniture-showcase/1-chairs/12-boucle-swivel-chair-with-side-table.webp": {
    "w": 834,
    "h": 587
  },
  "furniture-showcase/2-sofas/01-curved-modular-sofa-chocolate.webp": {
    "w": 1602,
    "h": 594
  },
  "furniture-showcase/2-sofas/02-rounded-sofa-white-boucle.webp": {
    "w": 1025,
    "h": 400
  },
  "furniture-showcase/2-sofas/03-serpentine-sofa-with-drum-table.webp": {
    "w": 1182,
    "h": 675
  },
  "furniture-showcase/2-sofas/04-modular-corner-sofa-ivory.webp": {
    "w": 1465,
    "h": 527
  },
  "furniture-showcase/2-sofas/05-channel-tufted-corner-sofa-with-console.webp": {
    "w": 1661,
    "h": 713
  },
  "furniture-showcase/2-sofas/06-chesterfield-sofa-tan-leather.webp": {
    "w": 1424,
    "h": 517
  },
  "furniture-showcase/2-sofas/07-sculpted-sofa-cream.webp": {
    "w": 1312,
    "h": 449
  },
  "furniture-showcase/2-sofas/08-pillow-back-sofa-dove-grey.webp": {
    "w": 1479,
    "h": 423
  },
  "furniture-showcase/2-sofas/09-swivel-lounge-chair-moss-velvet.webp": {
    "w": 828,
    "h": 645
  },
  "furniture-showcase/2-sofas/10-bubble-armchair-rust.webp": {
    "w": 698,
    "h": 566
  },
  "furniture-showcase/2-sofas/11-channel-tufted-loveseat-blush-velvet.webp": {
    "w": 943,
    "h": 586
  },
  "furniture-showcase/2-sofas/12-corner-sofa-with-nesting-marble-tables.webp": {
    "w": 1450,
    "h": 570
  },
  "furniture-showcase/2-sofas/13-chaise-sofa-ivory-linen-brass-feet.webp": {
    "w": 1382,
    "h": 519
  },
  "furniture-showcase/2-sofas/14-low-platform-corner-sofa.webp": {
    "w": 1738,
    "h": 554
  },
  "furniture-showcase/2-sofas/15-chaise-sofa-ivory.webp": {
    "w": 1479,
    "h": 455
  },
  "furniture-showcase/2-sofas/16-tufted-modular-sofa.webp": {
    "w": 1546,
    "h": 493
  },
  "furniture-showcase/2-sofas/17-lounge-set-two-armchairs-and-nesting-tables.webp": {
    "w": 1199,
    "h": 343
  },
  "furniture-showcase/3-beds/01-pleated-upholstered-bed.webp": {
    "w": 1305,
    "h": 1053
  },
  "furniture-showcase/3-beds/02-grid-panel-bed.webp": {
    "w": 1060,
    "h": 783
  },
  "furniture-showcase/3-beds/03-single-bed-forest-green-headboard.webp": {
    "w": 1117,
    "h": 1024
  },
  "furniture-showcase/3-beds/04-upholstered-bed-stone-linen.webp": {
    "w": 1134,
    "h": 867
  },
  "furniture-showcase/3-beds/05-tufted-bed-charcoal.webp": {
    "w": 1181,
    "h": 702
  },
  "furniture-showcase/3-beds/06-rounded-bed-navy-velvet.webp": {
    "w": 1223,
    "h": 797
  },
  "furniture-showcase/3-beds/07-scalloped-headboard-bed.webp": {
    "w": 923,
    "h": 704
  },
  "furniture-showcase/3-beds/08-walnut-bed-spindle-posts.webp": {
    "w": 1331,
    "h": 811
  },
  "furniture-showcase/3-beds/09-tall-channel-headboard-bed.webp": {
    "w": 1233,
    "h": 1002
  },
  "furniture-showcase/3-beds/10-low-upholstered-bed-ivory.webp": {
    "w": 1390,
    "h": 815
  },
  "furniture-showcase/3-beds/11-timber-panel-bed-with-nightstands.webp": {
    "w": 1451,
    "h": 904
  },
  "furniture-showcase/3-beds/12-oak-bed-with-cane-nightstands.webp": {
    "w": 1528,
    "h": 884
  },
  "furniture-showcase/3-beds/13-upholstered-bed-with-side-tables.webp": {
    "w": 1720,
    "h": 667
  },
  "furniture-showcase/3-beds/14-childs-bed-taupe-frame.webp": {
    "w": 1074,
    "h": 1037
  },
  "furniture-showcase/3-beds/15-walnut-panel-bed-suite.webp": {
    "w": 1640,
    "h": 926
  },
  "furniture-showcase/4-consoles/01-cane-front-sideboard-arched-doors.webp": {
    "w": 1438,
    "h": 876
  },
  "furniture-showcase/4-consoles/02-lacquered-sideboard-forest-green.webp": {
    "w": 1482,
    "h": 724
  },
  "furniture-showcase/4-consoles/03-sculpted-sideboard-white.webp": {
    "w": 1001,
    "h": 588
  },
  "furniture-showcase/4-consoles/04-walnut-chest-of-drawers.webp": {
    "w": 745,
    "h": 926
  },
  "furniture-showcase/4-consoles/05-walnut-media-console.webp": {
    "w": 1132,
    "h": 728
  },
  "furniture-showcase/4-consoles/06-birch-sliding-door-cabinet.webp": {
    "w": 1191,
    "h": 606
  },
  "furniture-showcase/4-consoles/07-half-moon-console-fan-front.webp": {
    "w": 884,
    "h": 887
  },
  "furniture-showcase/4-consoles/08-marble-top-sideboard-black-and-brass.webp": {
    "w": 1424,
    "h": 706
  },
  "furniture-showcase/4-consoles/09-console-table-sculpted-brass-base.webp": {
    "w": 962,
    "h": 999
  },
  "furniture-showcase/4-consoles/10-walnut-sideboard-marble-top.webp": {
    "w": 1531,
    "h": 586
  },
  "furniture-showcase/4-consoles/11-oak-and-cane-sideboard.webp": {
    "w": 1038,
    "h": 618
  },
  "furniture-showcase/4-consoles/12-walnut-sideboard-lattice-doors.webp": {
    "w": 1146,
    "h": 1046
  },
  "furniture-showcase/4-consoles/13-walnut-media-unit.webp": {
    "w": 1413,
    "h": 539
  },
  "furniture-showcase/4-consoles/14-fluted-console-white.webp": {
    "w": 826,
    "h": 1094
  },
  "furniture-showcase/4-consoles/15-rattan-media-console.webp": {
    "w": 1219,
    "h": 539
  },
  "furniture-showcase/4-consoles/16-demilune-sideboard-walnut-and-cane.webp": {
    "w": 1133,
    "h": 653
  },
  "furniture-showcase/4-consoles/17-console-table-brass-and-black-glass.webp": {
    "w": 672,
    "h": 829
  },
  "furniture-showcase/5-dining-tables/01-oval-dining-set-charcoal.webp": {
    "w": 1339,
    "h": 834
  },
  "furniture-showcase/5-dining-tables/02-plank-dining-table-steel-cross-base.webp": {
    "w": 1654,
    "h": 604
  },
  "furniture-showcase/5-dining-tables/03-oval-dining-table-fluted-pedestals.webp": {
    "w": 1508,
    "h": 635
  },
  "furniture-showcase/5-dining-tables/04-round-dining-set-curved-chairs.webp": {
    "w": 1419,
    "h": 899
  },
  "furniture-showcase/5-dining-tables/05-dining-set-for-six.webp": {
    "w": 1397,
    "h": 639
  },
  "furniture-showcase/5-dining-tables/06-dining-table-laid-for-six.webp": {
    "w": 1428,
    "h": 637
  },
  "furniture-showcase/5-dining-tables/07-walnut-dining-set-hairpin-legs.webp": {
    "w": 1253,
    "h": 744
  },
  "furniture-showcase/5-dining-tables/08-marble-dining-set-for-four.webp": {
    "w": 1133,
    "h": 1067
  },
  "furniture-showcase/5-dining-tables/09-round-oak-dining-set-fluted-pedestal.webp": {
    "w": 1346,
    "h": 918
  },
  "furniture-showcase/5-dining-tables/10-classic-round-dining-set.webp": {
    "w": 1346,
    "h": 981
  },
  "furniture-showcase/5-dining-tables/11-oak-dining-table-slab-legs.webp": {
    "w": 1348,
    "h": 644
  },
  "furniture-showcase/5-dining-tables/12-marble-dining-table-sculpted-bronze-base.webp": {
    "w": 1431,
    "h": 611
  },
  "furniture-showcase/5-dining-tables/13-marble-dining-table-fluted-columns.webp": {
    "w": 1431,
    "h": 563
  },
  "furniture-showcase/5-dining-tables/14-marble-dining-table-splayed-legs.webp": {
    "w": 1602,
    "h": 557
  },
  "furniture-showcase/5-dining-tables/15-walnut-dining-table-blade-legs.webp": {
    "w": 1549,
    "h": 560
  },
  "furniture-showcase/5-dining-tables/16-walnut-dining-table-folded-base.webp": {
    "w": 1665,
    "h": 573
  },
  "furniture-showcase/5-dining-tables/17-marble-dining-table-curved-bronze-legs.webp": {
    "w": 1500,
    "h": 668
  },
  "furniture-showcase/5-dining-tables/18-walnut-dining-table-fluted-plinth.webp": {
    "w": 1624,
    "h": 677
  },
  "furniture-showcase/5-dining-tables/19-round-oak-dining-table-conical-base.webp": {
    "w": 1253,
    "h": 838
  },
  "furniture-showcase/6-side-tables/01-marble-bowl-side-table.webp": {
    "w": 607,
    "h": 595
  },
  "furniture-showcase/6-side-tables/02-patterned-side-tables-with-globe-lamp.webp": {
    "w": 1064,
    "h": 741
  },
  "furniture-showcase/6-side-tables/03-marble-tray-side-table.webp": {
    "w": 501,
    "h": 835
  },
  "furniture-showcase/7-desks/01-walnut-desk-waterfall-edge.webp": {
    "w": 1351,
    "h": 771
  },
  "furniture-showcase/7-desks/02-writing-desk-and-chair-walnut.webp": {
    "w": 985,
    "h": 899
  },
  "furniture-showcase/8-coffee-tables/01-oval-coffee-table-patterned-base.webp": {
    "w": 929,
    "h": 362
  },
  "furniture-showcase/9-benches/01-tufted-bench-turned-walnut-legs.webp": {
    "w": 1083,
    "h": 430
  },
  "furniture-showcase/9-benches/02-channel-bench-brass-legs.webp": {
    "w": 1197,
    "h": 390
  },
  "ribbon/bimcad-workflow/03-nesting-optimization.webp": {
    "w": 1920,
    "h": 1038
  },
  "ribbon/bimcad-workflow/04-gis-site-terrain.webp": {
    "w": 1914,
    "h": 1040
  },
  "ribbon/bimcad-workflow/06-facade-paneling-script.webp": {
    "w": 1920,
    "h": 1042
  },
  "ribbon/bimcad-workflow/07-solar-wind-analysis.webp": {
    "w": 1920,
    "h": 1041
  },
  "ribbon/bimcad-workflow/08-environmental-analysis.webp": {
    "w": 1906,
    "h": 1039
  },
  "ribbon/bimcad-workflow/09-diagrid-pattern-script.webp": {
    "w": 1920,
    "h": 1041
  },
  "ribbon/ext-01-office-building.webp": {
    "w": 901,
    "h": 674
  },
  "ribbon/ext-02-gable-house.webp": {
    "w": 885,
    "h": 669
  },
  "ribbon/ext-03-apartment-facade.webp": {
    "w": 899,
    "h": 898
  },
  "ribbon/ext-10-tower-render.webp": {
    "w": 639,
    "h": 1200
  },
  "ribbon/ext-11-facade-closeup-render.webp": {
    "w": 1347,
    "h": 1200
  },
  "ribbon/ext-12-cube-facade-render.webp": {
    "w": 1317,
    "h": 1200
  },
  "ribbon/exterior-showcase/timber-cabin/02-3d-model.webp": {
    "w": 1362,
    "h": 1200
  },
  "ribbon/int-01-home-office.webp": {
    "w": 1600,
    "h": 1200
  },
  "ribbon/int-02-dark-living-room.webp": {
    "w": 1600,
    "h": 1200
  },
  "ribbon/int-03-bright-loft.webp": {
    "w": 1600,
    "h": 900
  },
  "ribbon/int-04-restaurant-interior.webp": {
    "w": 1334,
    "h": 1200
  },
  "ribbon/int-05-classical-dining.webp": {
    "w": 1600,
    "h": 900
  },
  "ribbon/int-07-lobby-lounge.webp": {
    "w": 1200,
    "h": 797
  },
  "ribbon/int-08-spiral-stair-library.webp": {
    "w": 1111,
    "h": 896
  },
  "ribbon/int-09-black-wall-living-room.webp": {
    "w": 1109,
    "h": 894
  },
  "ribbon/int-10-sunken-fire-pit-lounge.webp": {
    "w": 1103,
    "h": 896
  },
  "ribbon/int-11-bathroom-tub.webp": {
    "w": 1600,
    "h": 1200
  },
  "ribbon/int-12-bathroom-shower.webp": {
    "w": 1600,
    "h": 1200
  },
  "ribbon/parametric-furniture/2.webp": {
    "w": 1977,
    "h": 1200
  },
  "ribbon/screens/fractal-panel-script.webp": {
    "w": 1920,
    "h": 1039
  },
  "ribbon/screens/point-cloud-analysis.webp": {
    "w": 2760,
    "h": 1039
  },
  "ribbon/screens/point-pattern-script.webp": {
    "w": 1920,
    "h": 1040
  },
  "ribbon/screens/structural-and-analytical-model.webp": {
    "w": 3840,
    "h": 1041
  },
  "ribbon/sheets/02-kids-room-elevation-a.webp": {
    "w": 1985,
    "h": 1200
  },
  "ribbon/sheets/03-kids-room-elevation-b.webp": {
    "w": 2028,
    "h": 1200
  },
  "ribbon/sheets/05-foster-home-australia-axonometrics.webp": {
    "w": 1446,
    "h": 1200
  },
  "ribbon/sheets/beach-house-a011-first-level.webp": {
    "w": 1709,
    "h": 1200
  },
  "ribbon/sheets/beach-house-a012-second-level.webp": {
    "w": 1709,
    "h": 1200
  },
  "ribbon/sheets/beach-house-a021-elevations.webp": {
    "w": 1709,
    "h": 1200
  },
  "ribbon/sheets/cran-015-first-floor.webp": {
    "w": 1725,
    "h": 1200
  },
  "ribbon/sheets/cran-018-sections.webp": {
    "w": 1725,
    "h": 1200
  },
  "ribbon/sheets/flats-basement-plan.webp": {
    "w": 1597,
    "h": 1091
  },
  "ribbon/sheets/flats-section-quantities.webp": {
    "w": 1799,
    "h": 1090
  },
  "ribbon/sheets/slamburger-a01-floor-plans.webp": {
    "w": 1725,
    "h": 1200
  },
  "ribbon/sheets/slamburger-a04-lighting-electrical.webp": {
    "w": 1725,
    "h": 1200
  },
  "ribbon/sheets/slamburger-a06-kitchen-elevations.webp": {
    "w": 1725,
    "h": 1200
  },
  "ribbon/visualization-showcase/master-bathroom/01-isometric-view.webp": {
    "w": 1230,
    "h": 1200
  }
};

export const RIBBON_OF: Record<string, string> = {
  "bimcad-workflow/03-nesting-optimization.jpg": "ribbon/bimcad-workflow/03-nesting-optimization.webp",
  "bimcad-workflow/04-gis-site-terrain.jpg": "ribbon/bimcad-workflow/04-gis-site-terrain.webp",
  "bimcad-workflow/06-facade-paneling-script.jpg": "ribbon/bimcad-workflow/06-facade-paneling-script.webp",
  "bimcad-workflow/07-solar-wind-analysis.jpg": "ribbon/bimcad-workflow/07-solar-wind-analysis.webp",
  "bimcad-workflow/08-environmental-analysis.jpg": "ribbon/bimcad-workflow/08-environmental-analysis.webp",
  "bimcad-workflow/09-diagrid-pattern-script.jpg": "ribbon/bimcad-workflow/09-diagrid-pattern-script.webp",
  "bimcad-workflow/originals/03-barndominium-plan-and-script.webp": "bimcad-workflow/originals/03-barndominium-plan-and-script.webp",
  "bimcad-workflow/originals/04-slat-wall-model-and-script.webp": "bimcad-workflow/originals/04-slat-wall-model-and-script.webp",
  "exterior-showcase/pavilion-restaurant/02-3d-model.webp": "exterior-showcase/pavilion-restaurant/02-3d-model.webp",
  "exterior-showcase/timber-cabin/02-3d-model.webp": "ribbon/exterior-showcase/timber-cabin/02-3d-model.webp",
  "furniture-showcase/1-chairs/01-lounge-chair-cognac-velvet.webp": "furniture-showcase/1-chairs/01-lounge-chair-cognac-velvet.webp",
  "furniture-showcase/1-chairs/02-boucle-tub-chair-steel-frame.webp": "furniture-showcase/1-chairs/02-boucle-tub-chair-steel-frame.webp",
  "furniture-showcase/1-chairs/03-wave-lounge-chair-burgundy-velvet.webp": "furniture-showcase/1-chairs/03-wave-lounge-chair-burgundy-velvet.webp",
  "furniture-showcase/1-chairs/04-armchair-floral-linen-turned-walnut.webp": "furniture-showcase/1-chairs/04-armchair-floral-linen-turned-walnut.webp",
  "furniture-showcase/1-chairs/05-cocoon-armchair-ivory-and-oak.webp": "furniture-showcase/1-chairs/05-cocoon-armchair-ivory-and-oak.webp",
  "furniture-showcase/1-chairs/06-low-lounge-chair-chocolate-velvet.webp": "furniture-showcase/1-chairs/06-low-lounge-chair-chocolate-velvet.webp",
  "furniture-showcase/1-chairs/07-mid-century-lounge-chair-walnut-frame.webp": "furniture-showcase/1-chairs/07-mid-century-lounge-chair-walnut-frame.webp",
  "furniture-showcase/1-chairs/08-wrapped-armchair-ivory-on-walnut.webp": "furniture-showcase/1-chairs/08-wrapped-armchair-ivory-on-walnut.webp",
  "furniture-showcase/1-chairs/09-barrel-chair-oak-shell.webp": "furniture-showcase/1-chairs/09-barrel-chair-oak-shell.webp",
  "furniture-showcase/1-chairs/10-club-armchair-taupe-leather.webp": "furniture-showcase/1-chairs/10-club-armchair-taupe-leather.webp",
  "furniture-showcase/1-chairs/11-wingback-lounge-chair-oatmeal-knit.webp": "furniture-showcase/1-chairs/11-wingback-lounge-chair-oatmeal-knit.webp",
  "furniture-showcase/1-chairs/12-boucle-swivel-chair-with-side-table.webp": "furniture-showcase/1-chairs/12-boucle-swivel-chair-with-side-table.webp",
  "furniture-showcase/2-sofas/01-curved-modular-sofa-chocolate.webp": "furniture-showcase/2-sofas/01-curved-modular-sofa-chocolate.webp",
  "furniture-showcase/2-sofas/02-rounded-sofa-white-boucle.webp": "furniture-showcase/2-sofas/02-rounded-sofa-white-boucle.webp",
  "furniture-showcase/2-sofas/03-serpentine-sofa-with-drum-table.webp": "furniture-showcase/2-sofas/03-serpentine-sofa-with-drum-table.webp",
  "furniture-showcase/2-sofas/04-modular-corner-sofa-ivory.webp": "furniture-showcase/2-sofas/04-modular-corner-sofa-ivory.webp",
  "furniture-showcase/2-sofas/05-channel-tufted-corner-sofa-with-console.webp": "furniture-showcase/2-sofas/05-channel-tufted-corner-sofa-with-console.webp",
  "furniture-showcase/2-sofas/06-chesterfield-sofa-tan-leather.webp": "furniture-showcase/2-sofas/06-chesterfield-sofa-tan-leather.webp",
  "furniture-showcase/2-sofas/07-sculpted-sofa-cream.webp": "furniture-showcase/2-sofas/07-sculpted-sofa-cream.webp",
  "furniture-showcase/2-sofas/08-pillow-back-sofa-dove-grey.webp": "furniture-showcase/2-sofas/08-pillow-back-sofa-dove-grey.webp",
  "furniture-showcase/2-sofas/09-swivel-lounge-chair-moss-velvet.webp": "furniture-showcase/2-sofas/09-swivel-lounge-chair-moss-velvet.webp",
  "furniture-showcase/2-sofas/10-bubble-armchair-rust.webp": "furniture-showcase/2-sofas/10-bubble-armchair-rust.webp",
  "furniture-showcase/2-sofas/11-channel-tufted-loveseat-blush-velvet.webp": "furniture-showcase/2-sofas/11-channel-tufted-loveseat-blush-velvet.webp",
  "furniture-showcase/2-sofas/12-corner-sofa-with-nesting-marble-tables.webp": "furniture-showcase/2-sofas/12-corner-sofa-with-nesting-marble-tables.webp",
  "furniture-showcase/2-sofas/13-chaise-sofa-ivory-linen-brass-feet.webp": "furniture-showcase/2-sofas/13-chaise-sofa-ivory-linen-brass-feet.webp",
  "furniture-showcase/2-sofas/14-low-platform-corner-sofa.webp": "furniture-showcase/2-sofas/14-low-platform-corner-sofa.webp",
  "furniture-showcase/2-sofas/15-chaise-sofa-ivory.webp": "furniture-showcase/2-sofas/15-chaise-sofa-ivory.webp",
  "furniture-showcase/2-sofas/16-tufted-modular-sofa.webp": "furniture-showcase/2-sofas/16-tufted-modular-sofa.webp",
  "furniture-showcase/2-sofas/17-lounge-set-two-armchairs-and-nesting-tables.webp": "furniture-showcase/2-sofas/17-lounge-set-two-armchairs-and-nesting-tables.webp",
  "furniture-showcase/3-beds/01-pleated-upholstered-bed.webp": "furniture-showcase/3-beds/01-pleated-upholstered-bed.webp",
  "furniture-showcase/3-beds/02-grid-panel-bed.webp": "furniture-showcase/3-beds/02-grid-panel-bed.webp",
  "furniture-showcase/3-beds/03-single-bed-forest-green-headboard.webp": "furniture-showcase/3-beds/03-single-bed-forest-green-headboard.webp",
  "furniture-showcase/3-beds/04-upholstered-bed-stone-linen.webp": "furniture-showcase/3-beds/04-upholstered-bed-stone-linen.webp",
  "furniture-showcase/3-beds/05-tufted-bed-charcoal.webp": "furniture-showcase/3-beds/05-tufted-bed-charcoal.webp",
  "furniture-showcase/3-beds/06-rounded-bed-navy-velvet.webp": "furniture-showcase/3-beds/06-rounded-bed-navy-velvet.webp",
  "furniture-showcase/3-beds/07-scalloped-headboard-bed.webp": "furniture-showcase/3-beds/07-scalloped-headboard-bed.webp",
  "furniture-showcase/3-beds/08-walnut-bed-spindle-posts.webp": "furniture-showcase/3-beds/08-walnut-bed-spindle-posts.webp",
  "furniture-showcase/3-beds/09-tall-channel-headboard-bed.webp": "furniture-showcase/3-beds/09-tall-channel-headboard-bed.webp",
  "furniture-showcase/3-beds/10-low-upholstered-bed-ivory.webp": "furniture-showcase/3-beds/10-low-upholstered-bed-ivory.webp",
  "furniture-showcase/3-beds/11-timber-panel-bed-with-nightstands.webp": "furniture-showcase/3-beds/11-timber-panel-bed-with-nightstands.webp",
  "furniture-showcase/3-beds/12-oak-bed-with-cane-nightstands.webp": "furniture-showcase/3-beds/12-oak-bed-with-cane-nightstands.webp",
  "furniture-showcase/3-beds/13-upholstered-bed-with-side-tables.webp": "furniture-showcase/3-beds/13-upholstered-bed-with-side-tables.webp",
  "furniture-showcase/3-beds/14-childs-bed-taupe-frame.webp": "furniture-showcase/3-beds/14-childs-bed-taupe-frame.webp",
  "furniture-showcase/3-beds/15-walnut-panel-bed-suite.webp": "furniture-showcase/3-beds/15-walnut-panel-bed-suite.webp",
  "furniture-showcase/4-consoles/01-cane-front-sideboard-arched-doors.webp": "furniture-showcase/4-consoles/01-cane-front-sideboard-arched-doors.webp",
  "furniture-showcase/4-consoles/02-lacquered-sideboard-forest-green.webp": "furniture-showcase/4-consoles/02-lacquered-sideboard-forest-green.webp",
  "furniture-showcase/4-consoles/03-sculpted-sideboard-white.webp": "furniture-showcase/4-consoles/03-sculpted-sideboard-white.webp",
  "furniture-showcase/4-consoles/04-walnut-chest-of-drawers.webp": "furniture-showcase/4-consoles/04-walnut-chest-of-drawers.webp",
  "furniture-showcase/4-consoles/05-walnut-media-console.webp": "furniture-showcase/4-consoles/05-walnut-media-console.webp",
  "furniture-showcase/4-consoles/06-birch-sliding-door-cabinet.webp": "furniture-showcase/4-consoles/06-birch-sliding-door-cabinet.webp",
  "furniture-showcase/4-consoles/07-half-moon-console-fan-front.webp": "furniture-showcase/4-consoles/07-half-moon-console-fan-front.webp",
  "furniture-showcase/4-consoles/08-marble-top-sideboard-black-and-brass.webp": "furniture-showcase/4-consoles/08-marble-top-sideboard-black-and-brass.webp",
  "furniture-showcase/4-consoles/09-console-table-sculpted-brass-base.webp": "furniture-showcase/4-consoles/09-console-table-sculpted-brass-base.webp",
  "furniture-showcase/4-consoles/10-walnut-sideboard-marble-top.webp": "furniture-showcase/4-consoles/10-walnut-sideboard-marble-top.webp",
  "furniture-showcase/4-consoles/11-oak-and-cane-sideboard.webp": "furniture-showcase/4-consoles/11-oak-and-cane-sideboard.webp",
  "furniture-showcase/4-consoles/12-walnut-sideboard-lattice-doors.webp": "furniture-showcase/4-consoles/12-walnut-sideboard-lattice-doors.webp",
  "furniture-showcase/4-consoles/13-walnut-media-unit.webp": "furniture-showcase/4-consoles/13-walnut-media-unit.webp",
  "furniture-showcase/4-consoles/14-fluted-console-white.webp": "furniture-showcase/4-consoles/14-fluted-console-white.webp",
  "furniture-showcase/4-consoles/15-rattan-media-console.webp": "furniture-showcase/4-consoles/15-rattan-media-console.webp",
  "furniture-showcase/4-consoles/16-demilune-sideboard-walnut-and-cane.webp": "furniture-showcase/4-consoles/16-demilune-sideboard-walnut-and-cane.webp",
  "furniture-showcase/4-consoles/17-console-table-brass-and-black-glass.webp": "furniture-showcase/4-consoles/17-console-table-brass-and-black-glass.webp",
  "furniture-showcase/5-dining-tables/01-oval-dining-set-charcoal.webp": "furniture-showcase/5-dining-tables/01-oval-dining-set-charcoal.webp",
  "furniture-showcase/5-dining-tables/02-plank-dining-table-steel-cross-base.webp": "furniture-showcase/5-dining-tables/02-plank-dining-table-steel-cross-base.webp",
  "furniture-showcase/5-dining-tables/03-oval-dining-table-fluted-pedestals.webp": "furniture-showcase/5-dining-tables/03-oval-dining-table-fluted-pedestals.webp",
  "furniture-showcase/5-dining-tables/04-round-dining-set-curved-chairs.webp": "furniture-showcase/5-dining-tables/04-round-dining-set-curved-chairs.webp",
  "furniture-showcase/5-dining-tables/05-dining-set-for-six.webp": "furniture-showcase/5-dining-tables/05-dining-set-for-six.webp",
  "furniture-showcase/5-dining-tables/06-dining-table-laid-for-six.webp": "furniture-showcase/5-dining-tables/06-dining-table-laid-for-six.webp",
  "furniture-showcase/5-dining-tables/07-walnut-dining-set-hairpin-legs.webp": "furniture-showcase/5-dining-tables/07-walnut-dining-set-hairpin-legs.webp",
  "furniture-showcase/5-dining-tables/08-marble-dining-set-for-four.webp": "furniture-showcase/5-dining-tables/08-marble-dining-set-for-four.webp",
  "furniture-showcase/5-dining-tables/09-round-oak-dining-set-fluted-pedestal.webp": "furniture-showcase/5-dining-tables/09-round-oak-dining-set-fluted-pedestal.webp",
  "furniture-showcase/5-dining-tables/10-classic-round-dining-set.webp": "furniture-showcase/5-dining-tables/10-classic-round-dining-set.webp",
  "furniture-showcase/5-dining-tables/11-oak-dining-table-slab-legs.webp": "furniture-showcase/5-dining-tables/11-oak-dining-table-slab-legs.webp",
  "furniture-showcase/5-dining-tables/12-marble-dining-table-sculpted-bronze-base.webp": "furniture-showcase/5-dining-tables/12-marble-dining-table-sculpted-bronze-base.webp",
  "furniture-showcase/5-dining-tables/13-marble-dining-table-fluted-columns.webp": "furniture-showcase/5-dining-tables/13-marble-dining-table-fluted-columns.webp",
  "furniture-showcase/5-dining-tables/14-marble-dining-table-splayed-legs.webp": "furniture-showcase/5-dining-tables/14-marble-dining-table-splayed-legs.webp",
  "furniture-showcase/5-dining-tables/15-walnut-dining-table-blade-legs.webp": "furniture-showcase/5-dining-tables/15-walnut-dining-table-blade-legs.webp",
  "furniture-showcase/5-dining-tables/16-walnut-dining-table-folded-base.webp": "furniture-showcase/5-dining-tables/16-walnut-dining-table-folded-base.webp",
  "furniture-showcase/5-dining-tables/17-marble-dining-table-curved-bronze-legs.webp": "furniture-showcase/5-dining-tables/17-marble-dining-table-curved-bronze-legs.webp",
  "furniture-showcase/5-dining-tables/18-walnut-dining-table-fluted-plinth.webp": "furniture-showcase/5-dining-tables/18-walnut-dining-table-fluted-plinth.webp",
  "furniture-showcase/5-dining-tables/19-round-oak-dining-table-conical-base.webp": "furniture-showcase/5-dining-tables/19-round-oak-dining-table-conical-base.webp",
  "furniture-showcase/6-side-tables/01-marble-bowl-side-table.webp": "furniture-showcase/6-side-tables/01-marble-bowl-side-table.webp",
  "furniture-showcase/6-side-tables/02-patterned-side-tables-with-globe-lamp.webp": "furniture-showcase/6-side-tables/02-patterned-side-tables-with-globe-lamp.webp",
  "furniture-showcase/6-side-tables/03-marble-tray-side-table.webp": "furniture-showcase/6-side-tables/03-marble-tray-side-table.webp",
  "furniture-showcase/7-desks/01-walnut-desk-waterfall-edge.webp": "furniture-showcase/7-desks/01-walnut-desk-waterfall-edge.webp",
  "furniture-showcase/7-desks/02-writing-desk-and-chair-walnut.webp": "furniture-showcase/7-desks/02-writing-desk-and-chair-walnut.webp",
  "furniture-showcase/8-coffee-tables/01-oval-coffee-table-patterned-base.webp": "furniture-showcase/8-coffee-tables/01-oval-coffee-table-patterned-base.webp",
  "furniture-showcase/9-benches/01-tufted-bench-turned-walnut-legs.webp": "furniture-showcase/9-benches/01-tufted-bench-turned-walnut-legs.webp",
  "furniture-showcase/9-benches/02-channel-bench-brass-legs.webp": "furniture-showcase/9-benches/02-channel-bench-brass-legs.webp",
  "parametric-furniture/2.png": "ribbon/parametric-furniture/2.webp",
  "screenshots/3.JPG": "ribbon/screens/fractal-panel-script.webp",
  "screenshots/4.JPG": "ribbon/screens/point-pattern-script.webp",
  "screenshots/6.JPG": "ribbon/screens/structural-and-analytical-model.webp",
  "screenshots/7.JPG": "ribbon/screens/point-cloud-analysis.webp",
  "sheets/02-kids-room-elevation-a.webp": "ribbon/sheets/02-kids-room-elevation-a.webp",
  "sheets/03-kids-room-elevation-b.webp": "ribbon/sheets/03-kids-room-elevation-b.webp",
  "sheets/05-foster-home-australia-axonometrics.webp": "ribbon/sheets/05-foster-home-australia-axonometrics.webp",
  "sheets/beach-house-a011-first-level.webp": "ribbon/sheets/beach-house-a011-first-level.webp",
  "sheets/beach-house-a012-second-level.webp": "ribbon/sheets/beach-house-a012-second-level.webp",
  "sheets/beach-house-a021-elevations.webp": "ribbon/sheets/beach-house-a021-elevations.webp",
  "sheets/cran-015-first-floor.webp": "ribbon/sheets/cran-015-first-floor.webp",
  "sheets/cran-018-sections.webp": "ribbon/sheets/cran-018-sections.webp",
  "sheets/flats-basement-plan.webp": "ribbon/sheets/flats-basement-plan.webp",
  "sheets/flats-section-quantities.webp": "ribbon/sheets/flats-section-quantities.webp",
  "sheets/slamburger-a01-floor-plans.webp": "ribbon/sheets/slamburger-a01-floor-plans.webp",
  "sheets/slamburger-a04-lighting-electrical.webp": "ribbon/sheets/slamburger-a04-lighting-electrical.webp",
  "sheets/slamburger-a06-kitchen-elevations.webp": "ribbon/sheets/slamburger-a06-kitchen-elevations.webp",
  "visualization-showcase/master-bathroom/01-isometric-view.webp": "ribbon/visualization-showcase/master-bathroom/01-isometric-view.webp"
};
